class Product {
  static List p =[
    {
      "title": "Essence Mascara Lash Princess",
      "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzgZVkFrvhVgqfQFoJ4LDuzoohA8YPQh5ScwEQtQBKyA&s=10",
      "price" : "1,299",
      "oldPrice" : "1,299",
      "discount" : "-49%",
      "rating" : "4.6",
      "review" : "(120)",
    },
    {
      "title": "Eyeshadow Palette with Mirror",
      "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTInaQYameXmcPXQrhh73p0k30vmDeKR1Kd_ZD2cAmqqw&s=10",
      "price" : "599",
      "oldPrice" : "599",
      "discount" : "-25%",
      "rating" : "4.8",
      "review" : "(150)",
    },
    {
      "title": "Powder Canister",
      "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRw2SZrBrVZ5dJMuCqnvGNunu-IgCRl9buomQbjVPl3Vw&s=10",
      "price" : "10,599",
      "oldPrice" : "10,599",
      "discount" : "-59%",
      "rating" : "4.3",
      "review" : "(240)",
    },
    {
      "title": "Red Lipstick",
      "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVVobAQr2SGHaDXoBMb43OWYT-f2IGSA8Yl7zECPdl1Q&s=10",
      "price" : "299",
      "oldPrice" : "299",
      "discount" : "-10%",
      "rating" : "3.7",
      "review" : "(220)",
    },
    {
      "title": "Casual Shirt",
      "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQy7kICzfCeH4MqmGNfdIzmsOooaefwoCgrsIl9GvX-Q&s=10",
      "price" : "1,780",
      "oldPrice" : "1,780",
      "discount" : "-50%",
      "rating" : "4.5",
      "review" : "(300)",
    },
    {
      "title": "Puma Sneakers",
      "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0bAOXVpJyZAS-Bm8ePx6cfFQ2wJC0yfODlrIpD2G4pA&s",
      "price" : "2,230",
      "oldPrice" : "2,230",
      "discount" : "-37%",
      "rating" : "4.1",
      "review" : "(270)",
    },
    {
      "title": "Chanel Coco Noir Eau De",
      "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeDTP9wiN_gTz-yG5eZUSSI57qIYtjbfig46BN3_W35Q&s=10",
      "price" : "599",
      "oldPrice" : "599",
      "discount" : "-45%",
      "rating" : "4.4",
      "review" : "(100)",
    },
    {
      "title": "Dior J'adore",
      "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSq8m9u4-gjJwdXcBmBJsyinnNBIHRoTJxxooeqjAKEGw&s=10",
      "price" : "1,200",
      "oldPrice" : "1,200",
      "discount" : "-39%",
      "rating" : "4.1",
      "review" : "(210)",
    },
    {
      "title": "Noise Smart Watch",
      "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7lZB8VTC38TgHqDvkCc1rtlhsh__ATAb9A5VBozNfCA&s=10",
      "price" : "1,500",
      "oldPrice" : "1,500",
      "discount" : "-59%",
      "rating" : "4.9",
      "review" : "(500)",
    },
    {
      "title": "Gucci Bloom Eau de",
      "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqbEgpDS57oEWwn0EcJ3XePWEIeLSuMth4RZBXGNGEjg&s=10",
      "price" : "500",
      "oldPrice" : "500",
      "discount" : "-50%",
      "rating" : "4.7",
      "review" : "(140)",
    }

  ];
}