import 'package:project_3/model/product_Model.dart';

class Product {
  static List<ProductModel> p = <ProductModel>[
    // {
    //  "title": "Essence Mascara Lash Princess",
    // "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzgZVkFrvhVgqfQFoJ4LDuzoohA8YPQh5ScwEQtQBKyA&s=10",
    //  "price" : "1,299",
    //  "oldPrice" : "1,299",
    //  "discount" : "-49%",
    // "rating" : "4.6",
    //   "review" : "(120)",
    //  },
    //  {
    //     "title": "Eyeshadow Palette with Mirror",
    //  "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTInaQYameXmcPXQrhh73p0k30vmDeKR1Kd_ZD2cAmqqw&s=10",
    // "price" : "599",
    //  "oldPrice" : "599",
    //  "discount" : "-25%",
    //  "rating" : "4.8",
    //   "review" : "(150)",
    //  },
    //  {
    //    "title": "Powder Canister",
    //   "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRw2SZrBrVZ5dJMuCqnvGNunu-IgCRl9buomQbjVPl3Vw&s=10",
    //  "price" : "10,599",
    //  "oldPrice" : "10,599",
    // "discount" : "-59%",
    //  "rating" : "4.3",
    //  "review" : "(240)",
    //  },
    // {
    // "title": "Red Lipstick",
    // "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVVobAQr2SGHaDXoBMb43OWYT-f2IGSA8Yl7zECPdl1Q&s=10",
    //  "price" : "299",
    //   "oldPrice" : "299",
    //   "discount" : "-10%",
    // "rating" : "3.7",
    //"review" : "(220)",
    // },
    // {
    //"title": "Casual Shirt",
    // "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQy7kICzfCeH4MqmGNfdIzmsOooaefwoCgrsIl9GvX-Q&s=10",
    //  "price" : "1,780",
    //"oldPrice" : "1,780",
    // "discount" : "-50%",
    //  "rating" : "4.5",
    // "review" : "(300)",
    //},
    // {
    // "title": "Puma Sneakers",
    // "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0bAOXVpJyZAS-Bm8ePx6cfFQ2wJC0yfODlrIpD2G4pA&s",
    //   "price" : "2,230",
    //   "oldPrice" : "2,230",
    //   "discount" : "-37%",
    //   "rating" : "4.1",
    //   "review" : "(270)",
    // },
    // {
    //   "title": "Chanel Coco Noir Eau De",
    //   "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeDTP9wiN_gTz-yG5eZUSSI57qIYtjbfig46BN3_W35Q&s=10",
    //   "price" : "599",
    //   "oldPrice" : "599",
    //   "discount" : "-45%",
    //   "rating" : "4.4",
    //   "review" : "(100)",
    // },
    // {
    //   "title": "Dior J'adore",
    //   "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSq8m9u4-gjJwdXcBmBJsyinnNBIHRoTJxxooeqjAKEGw&s=10",
    //   "price" : "1,200",
    //   "oldPrice" : "1,200",
    //   "discount" : "-39%",
    //   "rating" : "4.1",
    //   "review" : "(210)",
    // },
    // {
    //   "title": "Noise Smart Watch",
    //   "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7lZB8VTC38TgHqDvkCc1rtlhsh__ATAb9A5VBozNfCA&s=10",
    //   "price" : "1,500",
    //   "oldPrice" : "1,500",
    //   "discount" : "-59%",
    //   "rating" : "4.9",
    //   "review" : "(500)",
    // },
    // {
    //   "title": "Gucci Bloom Eau de",
    //   "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqbEgpDS57oEWwn0EcJ3XePWEIeLSuMth4RZBXGNGEjg&s=10",
    //   "price" : "500",
    //   "oldPrice" : "500",
    //   "discount" : "-50%",
    //   "rating" : "4.7",
    //   "review" : "(140)",
    // }
    ProductModel(
      id: 1001,
      title: "HeadPhone",
      oldPrice: 3550,
      discount: 2500,
      review: "320",
      rating: 4.6,
      imageUrl:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsuHAJCW-qz5sZZQS8fORe9zNEXzjZm9WTJerrJwOx1A&s=10",
    ),
    ProductModel(
      id: 1002,
      title: "T-Shart",
      oldPrice: 2000,
      discount: 1500,
      review: "320",
      rating: 4.5,
      imageUrl:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2k07qd4GYmL5Elcu0wyUf54BJiXaUizI-U0YY4WsoNA&s=10",
    ),
    ProductModel(
      id: 1003,
      title: "Smart watch",
      oldPrice: 1200,
      discount: 1000,
      review: "320",
      rating: 4.2,
      imageUrl:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfXOHfdtnqTbdBMvt412pKBqwKtu-uvM6jFQLD9v2c1g&s=10",
    ),
    ProductModel(
      id: 1004,
      title: "Panjabi",
      oldPrice: 3500,
      discount: 3000,
      review: "320",
      rating: 4.4,
      imageUrl:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcSLbxWZNZQ-8J28PfdPg5bULUoW4l40GvwTkFcusT7w&s=10",
    ),
    ProductModel(
      id: 1005,
      title: "Mobile Phone",
      oldPrice: 33000,
      discount: 30000,
      review: "320",
      rating: 4.9,
      imageUrl:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyO0oeJPptsVeRvxxncnTuutKw3d6Ay-xHhEpPEG31rg&s=10",
    ),
  ];
}
